### ISSUE TITLE
Morning session: Peer-to-peer code review

### ISSUE THREAD

**Issue by ghreza-crypto** [ClintonYounge/To-Do-List-Project#9]
Very good work my friend I think everything is nice, especially with your JavaScript files, you have done nice and professional coding but one thing I want to mention is about CSS best practice guides that are better to use classes not id selectors for styling, I realized that you have used id selectors for your stylings. 
well done my friend.

**Comment by ClintonYounge** [comment]
Thanks. Will address it!
